version: '3.8'

services:
  # Backend API service
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shelter_surfing
      - JWT_SECRET=your-development-secret
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_SOCKET_URL=ws://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

  # Database service
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shelter_surfing
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 